### ISSUE TITLE
Need source files for .png images

### ISSUE THREAD

**Issue by ghost** [GSA/ficam-playbooks#55]
#### Description of Issue: #### 
Unable to update .png images without the source file used to create the .png - Visio, Gliffy, etc.

#### References (Docs, Links, Files): #### 
All of the files in [https://github.com/GSA/ficam-arch/tree/staging/img](https://github.com/GSA/ficam-arch/tree/staging/img) are .PNG image files and not easily editable to make changes and improvements to.

**Comment by maxwellfunk** [comment]
.pptx files added to /assets/arch/Source_Images/

**Comment by maxwellfunk** [comment]
now in staging.
