### ISSUE TITLE
How to Digitally Sign and Encrypt Email- Guide for Agency employees and contractors

### ISSUE THREAD

**Issue by weirdscience** [GSA/ficam-playbooks#77]
Copied from FPKI Guide. A user guide focused on cloud email. Cloud email because that is the technology direction.

Security/Manager Guide (?) - Alignment with 800-53 controls (?)
Engineer Guide - How to enable digitally signed and encrypted email in Office 365 and Gmail.
User Guide - How to sign and encrypt in email in Outlook for Web and Gmail / How to verify a digitally signed email.

Special Considerations - Archive and e-discovery of encrypted emails.

**Comment by maxwellfunk** [comment]
cloud based email solutions might be a challenge due to required S/MIME plugins and may not even support enterprise PKI (e.g. not related to cloud offering)

**Comment by ryancdickson** [comment]
I've attempted to install the [S/MIME extension](https://microsoftedge.microsoft.com/addons/detail/microsoft-smime/gamjhjfeblghkihfjdpmbpajhlpmobbp) on my personal machine using Chrome, Edge, and IE - with no success.  

It's possible a local configuration is preventing the extension from working properly - so I'll try again using one of the AWS instances.

**Comment by maxwellfunk** [comment]
now in staging

**Comment by maxwellfunk** [comment]
creating a new issue to extend a table for additional guidance for web client plugins
