### ISSUE TITLE
MacOSX and Network Auth

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-playbooks#80]
For MacOSX and _network authentication_ (aka bound to a network domain), NIH has a private repository for a plugin that builds upon the native smart card apis.  
- https://github.com/NIH-CIT/NIHAuthPlugin

There are also commercially available options.
Need to add a section under network for MacOSX and considerations.

**Comment by maxwellfunk** [comment]
level of detail - separate page, define problem statement, add links to resource.

**Comment by maxwellfunk** [comment]
First draft incorporated into the following branch:
https://github.com/GSA/ficam-playbooks/tree/MacOS_AuthN

**Comment by maxwellfunk** [comment]
currently requested to have NASA review draft content:
https://federalist-db14ea61-37f0-44fd-8ab9-591433f0ec2b.app.cloud.gov/preview/gsa/ficam-playbooks/MacOS_AuthN/piv/network/mac/

**Comment by idmken** [comment]
I tested this - https://support.apple.com/guide/deployment-reference-macos/using-a-smart-card-in-macos-apd4ff986f6a/web on my machine and it worked. But its not network or directory joined to anything
