### ISSUE TITLE
Error logging to enable on domains for troubleshooting

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-playbooks#82]
Add information, configurations and scripts for which error logs to enable on network domains for enterprise engineers to troubleshoot. 

List of the common errors encountered mapped to primary and secondary _troubleshooting_ specific to federal agencies

**Comment by idmken** [comment]
Scope it to what are the most common smart card authentication issues and resolutions.

**Comment by maxwellfunk** [comment]
two options:
1. FAQ and/or
2. CAPI logging
