### ISSUE TITLE
Logon script that sets friendly name

### ISSUE THREAD

**Issue by lachellel** [GSA/ficam-playbooks#85]
- Using a logon script on managed devices to set friendly names for person certs
- Applies to applications and ease of use for users

Need sample scripts

**Comment by idmken** [comment]
@ryancdickson is this similar to the script to import certs for altsecids?

**Comment by ryancdickson** [comment]
@idmken - Not quite.

I think the goal described in this issue would automatically assign a friendly name to a user's PIV credential certificates upon logging onto the intended system. 

Populating the "Friendly Name" attribute can make it easier for end-users to distinguish certificates (i.e., authentication versus signature).  Not all products support use of "Friendly Name" --- looking quickly, it seems as if IE does, but Chrome does not.

Sample screenshots of manually setting "friendly name" --- and IE presenting it are attached.


![Friendly-1](https://user-images.githubusercontent.com/4267517/125666358-90d3c19a-6556-433e-9c86-113b64b27112.png)
![Friendly-2](https://user-images.githubusercontent.com/4267517/125666356-6c67cbce-4fa3-4091-9176-39bcefb1f7f5.png)
![Friendly-3](https://user-images.githubusercontent.com/4267517/125666357-b8400d39-2478-4c05-8771-1f5c64e2bfba.png)

**Comment by maxwellfunk** [comment]
potentially test with Edge to see if friendly name is still applicable, if not close.

**Comment by ryancdickson** [comment]
Edge presents friendly name, observed in the following image:

![edge-friendly-name-07232021](https://user-images.githubusercontent.com/4267517/126778597-4a89cc57-17cc-4186-b717-110c5f4d447a.png)

**Comment by maxwellfunk** [comment]
We believe this issue to be OBE due to the following reasons:

1. the Common (and soon to be bridge) profile updates which disallowed any key usage in EKU has been in effect for almost 3 years
2. recent updates to the profiles have incorporated specific EKUs for the signing cert which would prevent them from being presented in a credential tile screen upon mutual TLS auth
3. Several PIV issuers already append the CN with (A, E, S) for its specific use

**Comment by grandamp** [comment]
Some notes:

- 2: Unless the issuer asserts TLS Client EKU in signature cert.

- 3: Only one issuer (HHS) appends -A, -E, -S

**Comment by maxwellfunk** [comment]
we also know that modifying the friendly name will not affect the experience for chrome users (assumedly 90% of the user base), and we have no known cert examples of user signature certs with SC auth or TLS client auth in the EKU currently.

**Comment by maxwellfunk** [comment]
Closing issue per previous discussions and lack of impact.
